#!/bin/bash

# Interactive shell
[[ $- != *i* ]] && return

set -o nounset

# Imports
source "${HOME}"/.bash.d/shopt.sh
source "${HOME}"/.bash.d/colors.sh
source "${HOME}"/.bash.d/export.sh
source "${HOME}"/.bash.d/alias.sh
source "${HOME}"/.bash.d/functions.sh
source "${HOME}"/.bash.d/prompt.sh
source "${HOME}"/.bash.d/binds.sh

# Call functions
__run_ssh_agent
__apply_dircolors
__run_bash_completion
__run_git_bash_prompt
__validate_java

# Set PATH
if [ -d "$HOME/.local/bin" ]; then
	PATH="$HOME/.local/bin:$PATH"
fi
