[General]
FullscreenOnStartup=false
Menu%20Font%20Directory=~/.local/share/fonts
MenuOnStartup=false
MouseHideOnTimeout=5
PlaylistFile=~/.config/projectM/presets
Title%20Font%20Directory=~/.local/share/fonts
playlistDockLocation=0
playlistDocked=true
playlistPath=~/.config/projectM
playlistPos=@Point(0 0)
playlistWindowSize=@Size(315 111)
pos=@Point(168 313)
