[General]
FullscreenOnStartup=false
Menu%20Font%20Directory=/home/qwertzy/.local/share/fonts
MenuOnStartup=false
MouseHideOnTimeout=5
PlaylistFile=/home/qwertzy/.config/projectM/presets
Title%20Font%20Directory=/home/qwertzy/.local/share/fonts
playlistDockLocation=0
playlistDocked=true
playlistPath=/home/qwertzy/.config/projectM
playlistPos=@Point(0 0)
playlistWindowSize=@Size(315 111)
pos=@Point(168 313)
