[General]
PlaylistFile=/home/qwertzy/.config/projectM/presets
playlistDockLocation=0
playlistDocked=true
playlistPath=/home/qwertzy/.config/projectM
playlistPos=@Point(0 0)
playlistWindowSize=@Size(315 111)
pos=@Point(587 173)
