#! /usr/bin/env bash

alias ls="ls -CF --color=auto"
alias df="df -h --total"
alias mkdir="mkdir -pv"
alias free="free -mt"
alias wget="wget -c"
alias myip="curl ipv4.icanhazip.com"
alias grep="grep --color=auto"
alias less="less -iFMRSX -x4"
alias ncdu="ncdu --color=dark"
alias diff="diff --color=auto"
alias ip="ip -c"
alias cat="bat"
alias tree="tree -C"
alias tree-all="tree -aF -t --filesfirst -C"
alias most="most -w"
alias find-text="rg --column --line-number --no-heading --hidden --color=always --smart-case 2>/dev/null"
alias git_status="git status -sb --show-stash --ahead-behind"
alias git_commit_dry_run="git commit --dry-run --short --branch"
alias git_commit_amend_message="git commit --amend --only"
alias git_log_history="git log --pretty=format:'%C(10)%h %C(12)%ad %C(blue)%an %C(3)%s%C(auto)%d' --date=relative $@"
alias git_log_graph="git log --graph --pretty=format:'%Cred%h%Creset %ad %s%C(yellow) %d%Creset %C(bold blue)<%an>%Creset' --date=short"
alias git_log_everyone="git log --graph --pretty=format:'%C(10)%h %C(12)%ad %C(blue)%an %C(3)%s%C(auto)%d' --date=relative --abbrev-commit --decorate=short --branches --tags --remotes"
alias git_log_mine="git log --pretty=format:'%C(10)%h %C(12)%ad %C(yellow)%s%C(auto)%d' --date=relative --author='$(git config user.email)' --branches --tags --remotes"
alias git_search_message="git log --stat -i --grep"
alias git_search_message_all_branches="git log --stat -i --all --grep"
alias git_stash_save="git stash push -um"
alias git_show_modified_by_last_commit="git show --pretty="" --name-only"
alias git_tag_add="git tag ${1} && git push origin ${1}"
alias git_updated="git for-each-ref --sort='-authordate:iso8601' --format='%(authordate:relative) %09%09 %(refname:short)' refs/heads"
alias git_unadd="git reset"
alias git_revert="git reset --hard HEAD"
alias git_stash="git stash --include-untracked"

# TV
alias tv-small="nvidia-settings --assign CurrentMetaMode='HDMI-0: 1920x1080_60 +0+0 {viewportout=1840x1035+40+22} {ForceFullCompositionPipeline=On}'"
alias tv-big="nvidia-settings --assign CurrentMetaMode='nvidia-auto-select +0+0 {ForceFullCompositionPipeline=On}'"
