export PROMPT_COMMAND="history -a"
export SHELL="/usr/bin/bash"
export EDITOR="micro"
export BROWSER="brave"
export PAGER="less"
export GIT_EDITOR="${EDITOR}"
export USE_EDITOR="${EDITOR}"
export VISUAL="${EDITOR}"
export HISTCONTROL="erasedups:ignoredups:ignorespace"
export HISTSIZE=500000
export HISTFILESIZE=100000
export HISTIGNORE="&:[ ]*:exit:ls:bg:fg:history:clear"
export XDG_RUNTIME_DIR="${HOME}/.config/ssh$(id -u)"
export XDG_SESSION_TYPE="x11"
export XDG_CURRENT_DESKTOP="compiz"
export ALERT="${RED}"
export GCC_COLORS="error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01"
export SSH_AUTH_SOCK="${XDG_RUNTIME_DIR}/ssh-agent.socket"
export QT_QPA_PLATFORMTHEME="qt5ct"
export _JAVA_OPTIONS="-Dawt.useSystemAAFontSettings=on"
