font:
  normal:
    family: Liga mononoki
  size: 10
  use_thin_strokes: true
  scale_with_dpi: true

background_opacity: 0.85
gtk_theme_variant: dark
live_config_reload: true
draw_bold_text_with_bright_colors: true
dynamic_title: true

colors:
    primary:
        background: '#011627'
        foreground: "#ffffff"

    normal:
        black: "#222226"
        red: "#f841a0"
        green: "#25c141"
        yellow: "#fdf454"
        blue: "#2f9ded"
        magenta: "#f97137"
        cyan: "#19cde6"
        white: "#ffffff"

    bright:
        black: "#969696"
        red: "#f6188f"
        green: "#1ebb2b"
        yellow: "#fdf834"
        blue: "#2186ec"
        magenta: "#f85a21"
        cyan: "#12c3e2"
        white: "#ffffff"

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"
  save_to_clipboard: true

scrolling:
  history: 10000
  auto_scroll: false

tabspaces: 4
  
cursor:
  style: Block
  style:
    blinking: Always
    blink_interval: 500
  unfocused_hollow: true

visual_bell:
  animation: EaseOutExpo
  # duration: 0  # 20
  duration: 1  # 20

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }
  
shell:
  program: /usr/bin/tmux
  args:
    - new-session
    - -A
    - -D
    - -s
    - main
