require "packages.packer"
require "packages.install_plugins"

require "options"
require "keymaps"
require "colorscheme"

require "plugins.aerial"
require "plugins.better_escape"
require "plugins.cmp"
require "plugins.dap"
require "plugins.gitsigns"
--require "plugins.illuminate"
require "plugins.indent_blankline"
require "plugins.lsp.lspconfig"
require "plugins.lsp.mason"
require "plugins.lsp.null_ls"
require "plugins.lualine"
require "plugins.neotree"
require "plugins.scrollview"
require "plugins.telescope"
require "plugins.treesitter"
require "plugins.ufo"
require "plugins.which_key"
