#!/bin/sh

# WM
# -------------
exec fluxbox &
fbpid=$!

sleep 0.5
{
    # APPLICATIONS
    # -------------
    fittstool &
    dunst &
    conky -c ~/.config/conky/inforc &
    conky -c ~/.config/conky/authnetrc &
    skippy-xd --config ~/.config/skyppy-xd/skippy-xd.rc --start-daemon &
    netwmpager &

    # APPLETS
    # -------------
    # redshift-gtk &
    clipit &
    nm-applet &
    blueman-applet &
    volumeicon &
} &

wait $fbpid
