#!/bin/sh

# WM
# -------------
exec fluxbox &
fbpid=$!

sleep 0.5
{
    # APPLICATIONS
    # -------------
    fittstool &
    dunst &
    unclutter --timeout 3 --start-hidden &
    conky -c ~/.config/conky/inforc &
    conky -c ~/.config/conky/authnetrc &
    skippy-xd --config ~/.config/skyppy-xd/skippy-xd.rc --start-daemon &

    # APPLETS
    # -------------
    clipit &
    nm-applet &
    blueman-applet &
    volumeicon &
    flameshot &
    redshift-gtk &
} &

wait $fbpid
